= Virtual Machines
:source-highlighter: pygments

[.text-center]
Jochem Arends

== Introduction

Virtual Machine (VM) are programs that emulates computer hardware. 
Virtual machines make it possible to run programs that run programs that aren't written for your device.
In this document I'm going to explain how I wrote a virtual machine using {cpp}20.

== Little Computer 3

Little Computer 3 (LC-3) is an educational computer architecuture developed at the University of Texas at Austin.
The LC-3 has a simple yet versatile instruction set. 
Many programs for this architecture can be found online, which makes our VM easy to test.
Many resources for the LC-3 architecture can be found online, including an assembler and a C compiler.

== Registers

Registers are a type of computer memory that typically build into the CPU.
Registers are used by instructions.
The LC-3 has eight 16-bit general purpose registers, these are called `R0-R7`.
There's also a 16-bit program counter which is ofter referred to as `PC`.

== Instruction Encoding

The four most significant bits of an intruction form the opcode.
The LC-3 architecture knows 15 distinct operations, which are listed below in the form of an `enum class`, but can also be found in the ISA.

.opcodes.h
[source, cpp]
----
include::../inc/lc3/opcodes.h[tag=adoc]
----

== Instruction Decoding

Instructions consist of named bit sequences that occupy fixed sequence of bits. 

[cols="1,1",stripes=even]
|===
|Term |Bits

|Destination Register (`DR`)
|11..9

|Source Register (`SR`)
|11..9

|Source Register 1 (`SR1`)
|8..6

|Source Register 2 (`SR2`)
|2..0

|Base Register (`BaseR`)
|8..6

|5-bit Immediate Value (`imm5`)
|4..0

|6-bit Offset Value (`offset6`)
|5..0

|9-bit PC Offset Value (`PCoffset9`)
|8..0

|11-bit PC Offset Value (`PCoffset11`)
|10..0

|8-bit Trap Vector Value (`trapvect8`)
|7..0
|===

.types.h
[source, cpp]
----
include::../inc/lc3/types.h[tag=adoc]
    /* etc.. */
}

#endif
----

.encoding.h
[source, cpp]
----
include::../inc/lc3/encoding.h[tag=!ignore]
----

<<<

== Memory

The LC-3 architecture uses 16-bit wide addresses, each of these addresses refers to a 16-bit location in memory. 
As for now, a simple `std::array` can be used for memory.
We make type alias for allowing us to easily change its defenition in the future.
This can come in handy when we want to implement memory mapped IO.

.memory.h
[source, cpp]
----
include::../inc/lc3/memory.h[tag=!ignore]
----

<<<

== The CPU

Below I've pasted the declaration of a structure that represents a LC-3 CPU. It's quite a lot, but I will explain every member.

.cpu.h
[source, cpp]
----
include::../inc/lc3/cpu.h[tag=!ignore]
----

